version: "3.8"

services:
  web:
    build: .
    container_name: parstasmim_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    restart: always
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    container_name: postgres_db
    volumes:
      - parstasmim_postgres:/var/lib/postgresql/data
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"

volumes:
  parstasmim_postgres: