version: "3.8"

services:

  db:
    image: postgres:13-alpine
    container_name: postgres_db
    volumes:
      - parstasmim_postgres:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

volumes:
  parstasmim_postgres: